# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cb7563b0-4a87-45f1-912d-9a2880630ffc";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-6866b834-8fee-4adc-8093-86449da2f901".device =
    "/dev/disk/by-uuid/6866b834-8fee-4adc-8093-86449da2f901";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8923-F8EE";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/Games" = {
    device = "/dev/disk/by-uuid/5e9ec0a8-7d51-4ce5-a5ab-5c307cccfce6";
    fsType = "btrfs";
  };

  fileSystems."/mnt/Storage" = {
    device = "/dev/disk/by-uuid/b220709b-5f93-478a-864c-f17478b4ce9b";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-929c8f5d-65d8-452d-a8e7-bc66694656fd".device =
    "/dev/disk/by-uuid/929c8f5d-65d8-452d-a8e7-bc66694656fd";

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b6f1fa72-15d1-4c5d-8ddb-a25d996b390d"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
